### ISSUE TITLE
Implementation of Currency Formatter

### ISSUE THREAD

**Issue by Zoz-trk** [tahackr/coin-tracker#5]
- [x] Market Cap section is hard to read and analyze when the value is too large.
- [x] Implementing currency formatter would be great addition here.
- [x] Could be $NUMBER+B for billions +M for Millions etc. **Example: $513748441905 -> $513.7B**

**Comment by tahackr** [comment]
Used Intl.NumberFormat to format the Market Cap value. Also realized coins that have a price below 1 dollar, is rendered with 2 decimal places and it doesn't make any sense. So now we are conditionally rendering prices and if the price is under 1 dollar we render it with 6 decimal places.

**Comment by Zoz-trk** [comment]
2 decimal place is actually industry standart for most the application in terms of price metric.
Instead of showing this $0.563422, please show this: $0.56

**Comment by tahackr** [comment]
Prices of some popular alt coins like Shiba Inu [https://tr.investing.com/crypto/shiba-inu/shib-usd](url) would be rendered as $0.00. I think for those coins we can go for 6 decimal places. Coins that have a value over 1 dollar will be shown with 2 decimal places. Are you okay with this?
